apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.REGION }}-docker.pkg.dev/{{ .Values.PROJECT_ID }}/movie-guru/db:{{ .Values.IMAGE.TAG }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "mainpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: movieguru
  annotations:
    networking.gke.io/load-balancer-type: "INTERNAL"
    cloud.google.com/load-balancer-ip: movie-guru-internal-ip-db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: movieguru

spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP



