apiVersion: apps/v1
kind: Deployment
metadata:
  name: flows
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flows
  template:
    metadata:
      labels:
        app: flows
    spec:
      containers:
        - name: flows
          image: "{{ .REGION }}-docker.pkg.dev/{{ .PROJECT_ID }}/movie-guru/flows:{{ .IMAGE.TAG }}"
          ports:
            - containerPort: 3400
            - containerPort: 4000
          env:
            - name: POSTGRES_HOST
              value: db.movieguru.svc.cluster.local
            - name: PROJECT_ID
              value: {{ .PROJECT_ID }}
            - name: POSTGRES_DB_USER_PASSWORD
              value: "minimalpassword"
            - name: POSTGRES_DB_USER
              value: "minimal-user"
            - name: TABLE_NAME
              value: "movies"
            - name: POSTGRES_DB_NAME
              value: "fake-movies-db"
            - name: APP_VERSION
              value: "v1"
            - name: LOCATION
              value: {{ .REGION }}

---
apiVersion: v1
kind: Service
metadata:
  name: flows
spec:
  selector:
    app: flows
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 3400
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP

