apiVersion: apps/v1
kind: Deployment
metadata:
  name: flows
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flows
  template:
    metadata:
      labels:
        app: flows
    spec:
      containers:
        - name: flows
          image: "{{ .Values.REGION }}-docker.pkg.dev/{{ .Values.PROJECT_ID }}/movie-guru/flows:{{ .Values.IMAGE.TAG }}"
          ports:
            - containerPort: 3400
          env:
            - name: POSTGRES_HOST
              value: db.movieguru.svc.cluster.local
            - name: PROJECT_ID
              value: {{ .Values.PROJECT_ID }}
            - name: POSTGRES_DB_USER_PASSWORD
              value: "minimal"
            - name: POSTGRES_DB_USER
              value: "minimal-user"
            - name: TABLE_NAME
              value: "movies"
            - name: POSTGRES_DB_NAME
              value: "fake-movies-db"
            - name: APP_VERSION
              value: "v1"
            - name: LOCATION
              value: {{ .Values.REGION }}

---
apiVersion: v1
kind: Service
metadata:
  name: flows
spec:
  selector:
    app: flows
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 3400
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flows-route
  namespace: movieguru
spec:
  parentRefs:
    - name: movieguru-gateway 
      namespace: movieguru
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/flows"
      backendRefs:
        - name: flows
          port: 3400