apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: movieguru-gateway
  namespace: movieguru
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
  addresses:
    - type: NamedAddress
      value: movie-guru-external-ip