apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secret-provider
  namespace: movieguru
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/apphub-srinandans-test/secrets/postgres-main-user-secret/versions/1"
        path: "secret.txt"