apiVersion: apps/v1
kind: Deployment
metadata:
  name: flows
  namespace: {{.Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flows
  template:
    metadata:
      labels:
        app: flows
    spec:
      containers:
      - name: flows
        image: "{{ .Values.Config.Image.Repository }}/movie-guru-server:ghack-sre"
        command: ["/app/flows"]
        ports:
        - containerPort: 3401
        env:
        - name: POSTGRES_HOST
          value: db-service
        - name: PROJECT_ID
          value: {{ .Values.Config.projectID }}
        - name: POSTGRES_DB_USER_PASSWORD
          value: "minimal"
        - name: POSTGRES_DB_USER
          value: "minimal-user"
        - name: POSTGRES_DB_NAME
          value: "fake-movies-db"
        - name: TABLE_NAME
          value: "movies"
        - name: LOCATION
          value: {{ .Values.Config.geminiApiLocation }}
        - name: SIMPLE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: flows-service
  namespace: {{.Chart.Name }}
spec:
  selector:
    app: flows 
  ports:
  - protocol: TCP
    port: 3401 
    targetPort: 3401 
  type: ClusterIP