apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-user-js
  namespace: {{.Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mock-user-js
  template:
    metadata:
      labels:
        app: mock-user-js
    spec:
      containers:
      - name: mock-user-js
        image: "{{ .Values.Config.Image.Repository  }}/movie-guru-mockuser:ghack-sre"
        ports:
        - containerPort: 3400
        env:
        - name: PROJECT_ID
          value: {{ .Values.Config.projectID }}
        - name: LOCATION
          value: {{ .Values.Config.geminiApiLocation }}
---
apiVersion: v1
kind: Service
metadata:
  name: mockuser-service
  namespace: {{.Chart.Name }}
spec:
  selector:
    app: mock-user-js 
  ports:
  - protocol: TCP
    port: 80  # The port users will access the frontend on
    targetPort: 3400 # The port your frontend container is listening on
  type: ClusterIP