apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-user-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mock-user-js
  template:
    metadata:
      labels:
        app: mock-user-js
    spec:
      containers:
      - name: mock-user-js
        image: "{{ .Values.Image.repository }}/movie-guru-mockuser:ghack-sre"
        ports:
        - containerPort: 3400
        env:
        - name: PROJECT_ID
          value: {{ .Values.Config.projectID }}
        - name: LOCATION
          value: {{ .Values.Config.geminiApiLocation }}
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server 
  ports:
  - protocol: TCP
    port: 8080  # The port users will access the frontend on
    targetPort: 8080 # The port your frontend container is listening on
  type: ClusterIP