apiVersion: v1
kind: Namespace
metadata:
  name: locust
  labels:
    name: locust
---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-collector
  labels:
    name: otel-collector
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Chart.Name }}
  labels:
    name: {{.Chart.Name }}