<script>
  export default {
    name: 'Footer',
  };
</script>
<template>
    <footer class="bg-primary w-full text-text text-center py-4">
      Through the magic of AI, the Movie Guru tunes into your unique movie wavelength.
      The movie info, the actors, directors, and posters you find here are FAKE, and entirely generated by AI models. 🎬
    </footer>
</template>
  
