services:
  server:
    # build: 
    #   context: ./ghacks/practical-sre/webserver
    #   dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/o11y-movie-guru/movie-guru/chatserver:sre-5e670f8
    ports:
      - "8080:8080"
    restart: always
    command: /app/mockserver
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - LOCATION=${REGION}
      - ENABLE_METRICS=${ENABLE_METRICS}
  
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./ghacks/practical-sre/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./ghacks/practical-sre/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    depends_on:
      - master