services:

   
  server:
    image: europe-west4-docker.pkg.dev/movie-guru-ghack/movie-guru/chatserver:jylu5b1jc9
    command: /app/webserver
    ports:
      - 8081:8080
    environment:
      - POSTGRES_HOST=34.91.131.183
      - PROJECT_ID=movie-guru-ghack
      - POSTGRES_DB_USER_PASSWORD=minimal
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db
      - TABLE_NAME=movies
      - APP_VERSION=v1
      - LOCATION=europe-west4
      - LOCAL=true
      - FLOWS_URL=http://flows:3400
      - REDIS_HOST=34.13.202.106
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my_redis_pwd
      # - OTEL_EXPORTER_OTLP_INSECURE=true
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      # - OTEL_SERVICE_NAME=movieguru-backend-go
      # - OTEL_GO_X_EXEMPLAR=true
   