services:
  genkit-js:
    build: ./genkit
    ports: 
      - "4000:4000"
      - "3400:3400"
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=minimalpassword
      - POSTGRES_DB_USER=minimal-user
      - TABLE_NAME=movies
      - POSTGRES_DB_NAME=fake-movies-db
      - APP_VERSION=v1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=europe-west4
      - LOCAL=true
    volumes:
      - ./js/flows:/app
      - ./.key.json:/key.json
    working_dir: /app
    networks:
      - db-shared-network
networks:
  db-shared-network:
    external: true
  