services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: main
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning 
  flows:
    build: ./js/flows
    environment:
      - PROJECT_ID=$PROJECT_ID
      - LOCATION=us-central1
      - POSTGRES_HOST=db
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_USER_PASSWORD=minimal
      - TABLE_NAME=movies
      - POSTGRES_DB_NAME=fake-movies-db
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=ERROR
    volumes:
      - ./key.json:/key.json
  server:
    build: ./chat_server_go
    restart: always
    command: /app/webserver
    environment:
      - PROJECT_ID=$PROJECT_ID      
      - LOCATION=$REGION
      - POSTGRES_HOST=db
      - POSTGRES_DB_USER_PASSWORD=minimal
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db
      - TABLE_NAME=movies
      - APP_VERSION=static
      - USE_AUTH=false
      - CORS_STRICT=false # allows any origin to get through
      - FLOWS_URL=http://flows:3400
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - FEEDBACK_URL=https://${GENKIT_FEEDBACK_REGION}-${PROJECT_ID}.cloudfunctions.net/ext-firebase-ai-user-engagement-collectEngagement
    depends_on:
      - cache 
      - db
  frontend:
    build: ./frontend
    environment:
      - VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - VITE_GCP_PROJECT_ID=${PROJECT_ID}
      - VITE_FIREBASE_APPID=${FIREBASE_APPID}
      - VITE_CHAT_SERVER_URL=http://localhost:8080/api
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - frontend
