services:
  frontend:
    build: ./frontend
    ports:
      -  5173:5173
    environment:
      - VITE_CHAT_SERVER_URL=http://localhost:8081
    networks:
      - shared-network
  mock-user-js:
    build: ./js/mock-user
    ports:
      - "3404:3400"
    environment:
      - PROJECT_ID=$PROJECT_ID
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=us-central1
    volumes:
      - ./.key.json:/key.json
    networks:
      - shared-network
  server:
    build: ./chat_server_go
    command: /app/webserver
    ports:
      - 8081:8080
    environment:
      - POSTGRES_HOST=db
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=minimal
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db
      - TABLE_NAME=movies
      - LOCATION=europe-west4
      - SIMPLE=true
      - FLOWS_URL=http://flows:3401
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my_redis_pwd
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_SERVICE_NAME=movieguru-backend-go
      - OTEL_GO_X_EXEMPLAR=true
    networks:
      - shared-network
    depends_on:
      - cache
  flows:
    build: ./chat_server_go
    command: /app/flows
    ports:
      - "3401:3401"
    environment:
      - POSTGRES_HOST=db
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=minimal
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db
      - TABLE_NAME=movies
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=europe-west4
      - SIMPLE=true
    volumes:
      - ./.key.json:/key.json
    networks:
      - shared-network
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass my_redis_pwd
    networks:
      - shared-network
networks:
  shared-network:
    external: true