services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    networks:
      - db-shared-network
  flows:
    build: ./js/flows
    ports:
      - "3400:3400"
      - "4000:4000"
    environment:
      - PROJECT_ID=$PROJECT_ID
      - LOCATION=us-west1
      - POSTGRES_HOST=db
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_USER_PASSWORD=minimal
      - TABLE_NAME=movies
      - POSTGRES_DB_NAME=fake-movies-db
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
    volumes:
      - ./.key.json:/key.json
    networks:
      - db-shared-network    
  server:
    build: ./chat_server_go
    restart: always
    command: /app/webserver
    ports:
      - 8081:8080
    environment:
      - PROJECT_ID=$PROJECT_ID      
      - LOCATION=$REGION
      - POSTGRES_HOST=db
      - POSTGRES_DB_USER_PASSWORD=minimal
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db
      - TABLE_NAME=movies
      - APP_VERSION=v1_local
      - USE_AUTH=false
      - FLOWS_URL=http://flows:3400
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_SERVICE_NAME=movieguru-backend
      - OTEL_GO_X_EXEMPLAR=true
    depends_on:
      - cache 
      - otelcol
    networks:
      - movie-guru
      - db-shared-network
  frontend:
    build:
      context: ./frontend
      args:
        VITE_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        VITE_GCP_PROJECT_ID: ${PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDERID: ${FIREBASE_MESSAGING_SENDERID}
        VITE_FIREBASE_APPID: ${FIREBASE_APPID}
        VITE_CHAT_SERVER_URL: http://localhost:8081
    ports:
      - "4001:4000"
    networks:
      - movie-guru
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.105.0
    ports:
      - 4318:4318
      - 8888:8888
    volumes:
      - ./metrics/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - ./.key.json:/key.json
    environment:
      - PROJECT_ID=$PROJECT_ID
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
    networks:
      - movie-guru
networks:
  db-shared-network:
    external: true
  movie-guru: 
    driver: bridge