services:
  genkit:
    build: ./genkit
    ports: 
      - "4000:4000"
    environment:
      - POSTGRES_HOST=db
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=minimal
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db      
      - LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCAL=true
    volumes:
      - ./js/flows-js:/app
      - ./.key.json:/key.json
      - ./evaluators:/eval
    working_dir: /app
    networks:
      - shared-network
networks:
  shared-network:
    external: true
  