services:
  genkit-go:
    build: ./genkit
    ports: 
      - "4002:4000"
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=$POSTGRES_DB_USER_PASSWORD
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db      
      - LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCAL=true
    volumes:
      - ./chat_server_go:/app
      - ./.key.json:/key.json
    working_dir: /app/cmd/standaloneFlows
    networks:
      - db-shared-network
  genkit-js:
    build: ./genkit
    ports: 
      - "4003:4000"
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=$POSTGRES_DB_USER_PASSWORD
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db      
      - LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCAL=true
    volumes:
      - ./js/flows-js:/app
      - ./.key.json:/key.json
    working_dir: /app
    networks:
      - db-shared-network
networks:
  db-shared-network:
    external: true
  