services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass my_redis_pwd
    networks:
      - db-shared-network
  flows:
    build: ./js/flows
    ports:
      - "3400:3400"
      - "4000:4000"
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=minimalpassword
      - POSTGRES_DB_USER=minimal-user
      - TABLE_NAME=movies
      - POSTGRES_DB_NAME=fake-movies-db
      - APP_VERSION=v1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=europe-west4
      - LOCAL=true
    volumes:
      - ./.key.json:/key.json
    networks:
      - db-shared-network    
  server:
    build: ./chat_server_go
    command: /app/webserver
    ports:
      - 8081:8080
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - PROJECT_ID=$PROJECT_ID
      - POSTGRES_DB_USER_PASSWORD=minimalpassword
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_NAME=fake-movies-db
      - TABLE_NAME=movies
      - APP_VERSION=local
      - LOCATION=europe-west4
      - FLOWS_URL=http://flows:3400
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my_redis_pwd
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318
      - OTEL_SERVICE_NAME=movieguru-backend-go
      - OTEL_GO_X_EXEMPLAR=true
    depends_on:
      - cache 
    networks:
      - movie-guru
      - db-shared-network
  frontend:
    build: ./frontend
    ports:
      -  5173:5173
    environment:
      - VITE_CHAT_SERVER_URL=http://localhost:8080
    networks:
      - movie-guru
  # otelcol:
  #   image: otel/opentelemetry-collector-contrib:0.105.0
  #   ports:
  #     - 4318:4318
  #     - 8888:8888
  #   volumes:
  #     - ./metrics/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
  #     - ./.key.json:/key.json
  #   environment:
  #     - PROJECT_ID=$PROJECT_ID
  #     - GOOGLE_APPLICATION_CREDENTIALS=/key.json
  #   networks:
  #     - movie-guru

networks:
  db-shared-network:
    external: true
  movie-guru: 
    driver: bridge