export POSTGRES_DB_USER_PASSWORD="<enter password for the minimal-user>"
export POSTGRES_DB_MAIN_USER_PASSWORD="<enter the password for the main user>"
export POSTGRES_HOST="<enter public IP address of db>"
export PROJECT_ID="<enter project id>"
export POSTGRES_DB_USER="minimal-user"
export LOCATION="europe-west4"
export TABLE_NAME="movies"
export POSTGRES_DB_NAME="fake-movies-db"
export LOCAL="true"

