apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: pgvector/pgvector:pg17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: main
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: movieguru
  template:
    spec:
      containers:
      - name: update-db-init-image
        image: "{{ .Values.Config.Image.Repository }}/db-init:sre-v2"
        env:
        - name: DB_HOST
          value: "http://db-service.movieguru.svc.cluster.local:5432"
        - name: DB_USER
          value: main
        - name: DB_NAME
          value: fake-movies-db
        - name: DB_PASS
          value: main
      restartPolicy: Never
  backoffLimit: 4 # Optional: Define the number of retries before considering the Job as failed
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: movieguru
spec:
  selector:
    app: db 
  ports:
  - protocol: TCP
    port: 5432  
    targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: movieguru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: movieguru