version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass my_redis_pwd
  flows:
    build: .
    command: /app/flows
    ports:
      - "3401:3401"
    environment:
      - POSTGRES_HOST=34.147.105.1
      - PROJECT_ID=movie-guru-436117
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_USER_PASSWORD=letmeusethedb
      - TABLE_NAME=movies
      - POSTGRES_DB_NAME=fake-movies-db
      - APP_VERSION=v1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=europe-west4
      - LOCAL=true
    volumes:
      - ./.key.json:/key.json
  server:
    build: .
    command: /app/webserver
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_HOST=34.147.105.1
      - PROJECT_ID=movie-guru-436117
      - POSTGRES_DB_USER=minimal-user
      - POSTGRES_DB_USER_PASSWORD=letmeusethedb
      - TABLE_NAME=movies
      - POSTGRES_DB_NAME=fake-movies-db
      - APP_VERSION=v1
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
      - LOCATION=europe-west4
      - LOCAL=true
      - FLOWS_URL=http://flows:3401
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my_redis_pwd
    depends_on:
      - cache 